In [ ]:
import numpy
t1=(1,2,3,4)
arr=numpy.array(t1)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr2=[1,2,3,4]

In [ ]:
import numpy as np
np_ar=np.array(arr2)
np_ar

array([1, 2, 3, 4])

In [ ]:
#to add the ele
arr3=np.append(np_ar,[41,42,43,44])
arr3


array([ 1,  2,  3,  4, 41, 42, 43, 44])

In [ ]:
arr4=np.delete(arr3,np.where(arr3==2))
arr4

array([ 1,  3,  4, 41, 42, 43, 44])

In [ ]:
#delete no of values
arr5=np.setdiff1d(arr4,[41,3])
arr5

array([ 1,  4, 42, 43, 44])

In [ ]:
#delete val based on index
arr6=np.delete(arr3,[0,4,5])
arr6

array([ 2,  3,  4, 43, 44])

In [ ]:
#create new array
l1=[1,3,17,32,41,42,46,47,48,61,66]
ar=np.array(l1)

In [ ]:
#filter in numpy
ar<45

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [ ]:
ar[ar<45]

array([ 1,  3, 17, 32, 41, 42])

In [ ]:
#print the value less then 20 grter than 50
#for and operator and using &
#for and operator or using |
(ar>20)&(ar<50)

array([False, False, False,  True,  True,  True,  True,  True,  True,
       False, False])

In [ ]:
ar[(ar>20)&(ar<50)]

array([32, 41, 42, 46, 47, 48])

In [ ]:
#to replace the value
ar[ar==1]=601
ar

array([601,   3,  17,  32,  41,  42,  46,  47,  48,  61,  66])

In [ ]:
#to create array full of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#to cteate 1d full of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#to create 2d array full of zeros
#syntax --> np.zeros([num_of_rows,num_of_cols])
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#to create array full of ones
np.ones(5)


array([1., 1., 1., 1., 1.])

In [ ]:
#to create 2d array full of ones
#syntax --> np.zeros([num_of_rows,num_of_cols])
np.ones([3,5],dtype=int)


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#type convert the elements in array
#to find the numpy data type of elements present in array --> type
#type(ar)
ar.dtype

dtype('int64')

In [ ]:
#we can convert the values in array to various bits
#they are
#int 8, int 16, int 32, int 64
#float 16,float 32, float 64
#complex 64, complex 128
#unit 32, unit 16
ar1=np.zeros([2,4],dtype='int8')
ar1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [ ]:
ar1=np.zeros([2,4],dtype='float16')
ar1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)

In [ ]:
ar1=np.zeros([2,4],dtype='complex64')
ar1

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]], dtype=complex64)

In [ ]:
np.int16(ar1)

<ipython-input-25-0553849d71e8>:1: ComplexWarning: Casting complex values to real discards the imaginary part
  np.int16(ar1)


array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [ ]:
#1.)how to create range of the element as array
#2.)how to convert a 1d array to multidimentional array
#3.)how to create array of identity matrix
#4.)how to perform slicing in multidimensional array
#5.)how to find the mean,median,sum,variance,standard deviation of an array
n_ar[min(ar)+max(ar)]
n_ar

NameError: name 'n_ar' is not defined