In [ ]:
import numpy as np
ar1=np.arange(13)
ar1
len(ar1)

13

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
#identify matrix can be created using 2 functions
#eye() --> used to define both user defined rows and cols
#identity() -->used to define same number of rows and cols
#syntax --> np.identity(5) --> 5 is 5 rows and 5 cols
#syntax --> np.eye(3,4) --> 3 rows and 4 cols
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(5, dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [ ]:
reshaped_array=ar1.reshape(13,1)
reshaped_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
ar2=np.arange(25)
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
#to perform multidimentional slicing
ar2=np.arange(25).reshape(5,5)
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ar2.shape

(5, 5)

In [ ]:
#ar2[rows,columns,steps]
#ar2[rows_start_end,col_start,col_end,step]
ar2[0:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
ar2[0:3,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
ar2[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [ ]:
ar2[-4:-3,-4:-3]

array([[6]])

In [ ]:
ar2[-2:-4,-4:-2]

array([], shape=(0, 2), dtype=int64)

In [ ]:
ar2[-2:-4,-2:-4]

array([], shape=(0, 0), dtype=int64)

In [ ]:
ar2[-4:-2,-4:-2]

array([[ 6,  7],
       [11, 12]])

In [ ]:
ar3=np.arange(50).reshape(5,10)
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
np.sum(ar3)#sum of all numbers in matrix

1225

In [ ]:
np.sum(ar3,axis=0)#it adds the matrix numbers in column wise

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [ ]:
np.sum(ar3,axis=1)#it adds the matrix numbers in row wise

array([ 45, 145, 245, 345, 445])

In [ ]:
# mean-->average value
# median-->center value
# mode--> max num of repeted element
# variance-->median/total num of elements
# std-->square root of varience

In [ ]:
#linspace
#it is used to print the evenly separated pointed
#between 2 range of values
#linspace(start,end,num of values)
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [ ]:
np.linspace(12,30, 12, retstep=True)

(array([12.        , 13.63636364, 15.27272727, 16.90909091, 18.54545455,
        20.18181818, 21.81818182, 23.45454545, 25.09090909, 26.72727273,
        28.36363636, 30.        ]),
 1.6363636363636365)

In [ ]:
np.linspace(1,10,5,retstep=True)

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

In [ ]:
#random module
#to generate randam number between the range
#np.random.randint(start,end)
np.random.randint(40)

9

In [ ]:
np.random.randint(20,30 ,3)

array([23, 22, 25])

In [ ]:
#rand ()-->
#to get the randomly generated values from 0 to 1, based on uniform distribution
np.random.rand(4)

array([0.79931101, 0.80017887, 0.35616094, 0.00886452])

In [ ]:
np.random.randint(40)

37

In [ ]:
np.random.rand(4,3)

array([[0.23573633, 0.04767515, 0.92602343],
       [0.09271458, 0.68771103, 0.57403489],
       [0.66371064, 0.90938444, 0.14135768],
       [0.5922235 , 0.91361566, 0.52056825]])

In [ ]:
#rand()-->
#to get the randomly generated values from 0 to 1,based on
#normal lised distribution
np.random.randn(5)

array([-0.37793005, -1.75355949, -0.47260624,  1.64463528, -0.91098764])

In [ ]:
ar3.min()


0

In [ ]:
ar3.max()

49

In [ ]:
#to find the index value in list
l1=[41,41,48,47,46]
print(l1.index(47))
np1=np.array(l1)

3


In [ ]:
print(ar3.tolist())

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]


In [ ]:
print(ar3.index(47))

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [ ]:
#find the index of min and max value
ar3.argmin()

0

In [ ]:
ar3.argmax()

In [ ]:
np1.argmin()

0

In [ ]:
np1.argmax()

2

In [ ]:
np.tan(np1)


array([ 0.1606567 ,  0.1606567 ,  1.20012724, -0.12452757, -2.08661353])

In [ ]:
np.cos(np1)

array([-0.98733928, -0.98733928, -0.64014434, -0.99233547, -0.43217794])

In [ ]:
np.sin(np1)

array([-0.15862267, -0.15862267, -0.76825466,  0.12357312,  0.90178835])

In [ ]:
1/np.sin(np1)

array([-6.30426917, -6.30426917, -1.30165172,  8.0923746 ,  1.10890765])

In [ ]:
np.cos(np1)/np.sin(np1)

array([ 6.22445256,  6.22445256,  0.83324498, -8.03035035, -0.47924543])

In [ ]:
#task:1-->write a python code for the below logic?
#(1X4)+(2x5)+(3x6)=4+10+18=>32
np2=np.array([1,2,3])
np3=np.array([4,5,6])
np2*np3

array([ 4, 10, 18])

In [ ]:
sum(np2*np3)

32

In [ ]:
s=np.array(["swa","sab","jyo","cha","yag","nav","naga","mah","pra","var"])
p=np.array(["thi","dha","thi","dhu","guu","ya","sai","esh","sad","ma"])
sp=np.char.add(s,p)
sp

array(['swathi', 'sabdha', 'jyothi', 'chadhu', 'yagguu', 'navya',
       'nagasai', 'mahesh', 'prasad', 'varma'], dtype='<U7')

In [ ]:
n=np.array([1,2,3,8,9,7])
m=np.array([4,5,6])
len

<function len(obj, /)>

In [ ]:
np1=np.array([1,2,4,5,num,le,ns])
np1[np.isnan(np1)]

NameError: name 'num' is not defined

In [ ]:
#pandas
#import pands as pd
# pandas is defined as open source library that provides high performence data manipulation i python
# data analysis requires lot of processing such as restructuring, cleaning,mergin,manipulating etc..
# we prefer the pandas to perform the above functionalities coz it is fast , simple then other tools.
# pandas is built on numpy,numpy is required for operating pandas
#*******#

#1.)pandas series
# pandas series is a data structure with one
# dimensional labelled array
# it is a primary building block of dataframe, making its rows and columns
import numpy as np
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':100,'b':200,'c':300}
#syntax--> pandas.series(data=name,index=none,dtype=none,name=none,copy true or false)
#eg1
import pandas as pd
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [ ]:
type(pd.Series(my_data))

pandas.core.series.Series

In [ ]:
#series with lables
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(data=[print,len,sum])

0    <built-in function print>
1      <built-in function len>
2      <built-in function sum>
dtype: object

In [ ]:
def decor(fun):
    def inner():
        str1=fun()
        return str1.upper
    return inner()
@decor#it is the function call of decor
def greet():
    return "good morning"
print(greet())

GOOD MORNING


In [ ]:
class profile:
    @property
    def display(self):
        print("my name is sab")
p=profile()
p.display

my name is sab


In [ ]:
ser1=pd.Series([1,2,3,4,5],['USA','India','Canada','UK','Egypt'])
ser1

USA       1
India     2
Canada    3
UK        4
Egypt     5
dtype: int64

In [ ]:
ser1['USA']

1

In [ ]:
#acessing values using indexing
ser1[0]

1

In [ ]:
ser1[1:3]

India     2
Canada    3
dtype: int64

In [ ]:
ser2=pd.Series([5,6,7,8],['USA','Brazil','Canada','UK'])
ser2

USA       5
Brazil    6
Canada    7
UK        8
dtype: int64

In [ ]:
ser1+ser2

Brazil     NaN
Canada    10.0
Egypt      NaN
India      NaN
UK        12.0
USA        6.0
dtype: float64

In [ ]:
ser2['china']='duplicate'

In [ ]:
ser2.drop('Brazil')

USA               5
Canada            7
UK                8
china     duplicate
dtype: object

In [ ]:
#dataframe
#pd.dataframe(datas,rows_lable.col_lable)
df=pd.DataFrame(np.random.randn(5,4))
df

0         1         2         3
0 -0.055439 -0.887614 -2.049130 -0.175702
1 -1.132503  0.408433  0.521460 -0.590128
2 -0.738215  0.039937 -0.305596 -0.952232
3 -0.305843 -0.120673 -0.269569  1.398645
4  0.738352  0.608704  0.336983  1.171291

In [ ]:
dP=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
dP

W         X         Y         Z
A  0.544822 -0.102568 -0.430853  0.425798
B  0.142921  0.279589 -1.197578 -0.262144
C -0.613074  1.728214  0.312922 -0.749768
D  0.565994  0.048606 -0.515583  1.230740
E -1.230339  1.637483 -0.410665 -1.350145

In [ ]:
#to convert dictionary to dataframe
d={"col1":[1,2],"col2":[3,4],"col3":[5,6]}
d

{'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6]}

In [ ]:
df=pd.DataFrame(d,["row1","row2"])
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [ ]:
p={"prasad":[10,10,10],"varma":[10,10,10]}
p

{'prasad': [10, 10, 10], 'varma': [10, 10, 10]}

In [ ]:
pf=pd.DataFrame(p,["sub1","sub2","total sgpa"])
pf

prasad  varma
sub1            10     10
sub2            10     10
total sgpa      10     10

In [ ]:
df.T

row1  row2
col1     1     2
col2     3     4
col3     5     6

In [ ]:
df.index#--> get all the row names

Index(['row1', 'row2'], dtype='object')

In [ ]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.dtypes

col1    int64
col2    int64
col3    int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, row1 to row2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    2 non-null      int64
 1   col2    2 non-null      int64
 2   col3    2 non-null      int64
dtypes: int64(3)
memory usage: 172.0+ bytes


In [ ]:
df.values

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
df.axes

[Index(['row1', 'row2'], dtype='object'),
 Index(['col1', 'col2', 'col3'], dtype='object')]

In [ ]:
df.ndim

2

In [ ]:
df.size

6

In [ ]:
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [ ]:
df['col1']

row1    1
row2    2
Name: col1, dtype: int64

In [ ]:
type(df['col1'])

pandas.core.series.Series

In [ ]:
#to access multiple columns
df[['col1','col2']]

col1  col2
row1     1     3
row2     2     4

In [ ]:
df['col4']=df['col1']+df['col2']
df

col1  col2  col3  col4
row1     1     3     5     4
row2     2     4     6     6

In [ ]:
df['col5']=df['col2']+df['col3']
df

col1  col2  col3  col4  col5
row1     1     3     5     4     8
row2     2     4     6     6    10

In [ ]:
df.drop('col5',axis=1)

col1  col2  col3  col4
row1     1     3     5     4
row2     2     4     6     6

In [ ]:
df

col1  col2  col3  col4  col5
row1     1     3     5     4     8
row2     2     4     6     6    10

In [ ]:
df.drop('col4', axis=1, inplace=True)
df

col1  col2  col3  col5
row1     1     3     5     8
row2     2     4     6    10

In [ ]:
df


col1  col2  col3  col5
row1     1     3     5     8
row2     2     4     6    10